branches:
  only:
    - master
gemfile:
  - Gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - env: COVERAGE=1
      gemfile: Gemfile
      rvm: 2.1.0
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
script: bundle exec rspec
