branches:
  only:
    - master
gemfile:
  - gemfiles/activerecord_4_0.gemfile
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - env: COVERAGE=1
      gemfile: Gemfile
      rvm: 2.3.6
rvm:
  - 2.2.2
  - 2.4.1
  - ruby-head
script: bundle exec rspec
