branches:
  only:
    - master
gemfile:
  - Gemfile
  - gemfiles/activerecord_5_2.gemfile
  - gemfiles/activerecord_6_0.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - env: COVERAGE=1
      gemfile: Gemfile
      rvm: 2.6.5
rvm:
  - 2.6.5
  - ruby-head
script: bundle exec rspec
