---
name: Tests
'on':
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7.5
          gemfile: gemfiles/activerecord_6_1.gemfile
        - ruby: 3.0.2
          gemfile: gemfiles/activerecord_6_1.gemfile
        - ruby: 3.0.5
          gemfile: gemfiles/activerecord_7_0.gemfile
        - ruby: ruby-head
          gemfile: Gemfile
        - ruby: ruby-head
          gemfile: gemfiles/activerecord_6_1.gemfile
        - ruby: 2.7.5
          gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v3
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install bundler:2.2.33
        bundle install --no-deployment
    - name: Run tests
      run: bundle exec rspec
